### ISSUE TITLE
Please update your peer dependency to work with sandbpack 2x version

### ISSUE THREAD

**Issue by IgorFilippov3** [AaronPowell96/sandpack-file-explorer#1]
Rn, I am getting this message every time I want to use your component with Sandpack v2+

Could not resolve dependency: peer @codesandbox/sandpack-react@"^1.18.0" from sandpack-file-explorer@0.0.4

**Comment by AaronPowell96** [comment]
Hey I just saw your email, didn't see a notification for this. If you raise a PR I can approve I am currently away! Also feel free to fork, there's so many improvements that can be done here I just never had the time to come back to it.

**Comment by AaronPowell96** [comment]
@IgorFilippov3 I've raised 0.0.5 release hope that helps!
